// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIynxNZXENTRWhqF6fW4GBA2YjZ0-rMqA',
    appId: '1:106218873843:android:4a26aedf3017fe3ee66886',
    messagingSenderId: '106218873843',
    projectId: 'talent-app-f191f',
    storageBucket: 'talent-app-f191f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjCfV8dFAqErKE3U3INZc3Zq5pLXKVZQ',
    appId: '1:106218873843:ios:37d646b739b25350e66886',
    messagingSenderId: '106218873843',
    projectId: 'talent-app-f191f',
    storageBucket: 'talent-app-f191f.appspot.com',
    androidClientId: '106218873843-3sgr97r8p06962nsagv18v80h2i2g4fh.apps.googleusercontent.com',
    iosClientId: '106218873843-nm0ofl92dphauba0501plvpcc0bfn18r.apps.googleusercontent.com',
    iosBundleId: 'com.enriqueespada.talentapp',
  );
}
